-- AlterTable
ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "showStampField" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "showRewardField" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "showStatusField" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "showBroadcastField" BOOLEAN NOT NULL DEFAULT true;
